// automatically generated by the FlatBuffers compiler, do not modify

package Client

const (
	CSPacketTypeLogin = 1
	CSPacketTypeMove = 2
	CSPacketTypeShoot = 3
)

var EnumNamesCSPacketType = map[int]string{
	CSPacketTypeLogin:"Login",
	CSPacketTypeMove:"Move",
	CSPacketTypeShoot:"Shoot",
}

