// automatically generated by the FlatBuffers compiler, do not modify

package Client

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CSShoot struct {
	_tab flatbuffers.Table
}

func GetRootAsCSShoot(buf []byte, offset flatbuffers.UOffsetT) *CSShoot {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CSShoot{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *CSShoot) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CSShoot) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CSShoot) Shell(obj *Shell) *Shell {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(Shell)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func CSShootStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func CSShootAddShell(builder *flatbuffers.Builder, shell flatbuffers.UOffsetT) {
	builder.PrependStructSlot(0, flatbuffers.UOffsetT(shell), 0)
}
func CSShootEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
