// automatically generated by the FlatBuffers compiler, do not modify

package Client

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SCLeaveOther struct {
	_tab flatbuffers.Table
}

func GetRootAsSCLeaveOther(buf []byte, offset flatbuffers.UOffsetT) *SCLeaveOther {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SCLeaveOther{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SCLeaveOther) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SCLeaveOther) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SCLeaveOther) AccountID() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SCLeaveOther) MutateAccountID(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func SCLeaveOtherStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SCLeaveOtherAddAccountID(builder *flatbuffers.Builder, accountID int32) {
	builder.PrependInt32Slot(0, accountID, 0)
}
func SCLeaveOtherEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
