// automatically generated by the FlatBuffers compiler, do not modify

package Client

const (
	SCPacketTypeLogin = 1
	SCPacketTypeEnter = 2
	SCPacketTypeEnterOther = 3
	SCPacketTypeLeaveOther = 4
	SCPacketTypeMove = 5
	SCPacketTypeShoot = 6
)

var EnumNamesSCPacketType = map[int]string{
	SCPacketTypeLogin:"Login",
	SCPacketTypeEnter:"Enter",
	SCPacketTypeEnterOther:"EnterOther",
	SCPacketTypeLeaveOther:"LeaveOther",
	SCPacketTypeMove:"Move",
	SCPacketTypeShoot:"Shoot",
}

