// automatically generated by the FlatBuffers compiler, do not modify

package Client

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SCShoot struct {
	_tab flatbuffers.Table
}

func GetRootAsSCShoot(buf []byte, offset flatbuffers.UOffsetT) *SCShoot {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SCShoot{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SCShoot) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SCShoot) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SCShoot) Shell(obj *Shell) *Shell {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(Shell)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func SCShootStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SCShootAddShell(builder *flatbuffers.Builder, shell flatbuffers.UOffsetT) {
	builder.PrependStructSlot(0, flatbuffers.UOffsetT(shell), 0)
}
func SCShootEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
