// automatically generated by the FlatBuffers compiler, do not modify

package Client

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type User struct {
	_tab flatbuffers.Struct
}

func (rcv *User) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *User) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *User) Num() int32 {
	return rcv._tab.GetInt32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *User) MutateNum(n int32) bool {
	return rcv._tab.MutateInt32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *User) Pos(obj *Vec3) *Vec3 {
	if obj == nil {
		obj = new(Vec3)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+4)
	return obj
}
func (rcv *User) Rot(obj *Qua) *Qua {
	if obj == nil {
		obj = new(Qua)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+16)
	return obj
}
func (rcv *User) Time() float32 {
	return rcv._tab.GetFloat32(rcv._tab.Pos + flatbuffers.UOffsetT(32))
}
func (rcv *User) MutateTime(n float32) bool {
	return rcv._tab.MutateFloat32(rcv._tab.Pos+flatbuffers.UOffsetT(32), n)
}

func CreateUser(builder *flatbuffers.Builder, num int32, pos_x float32, pos_y float32, pos_z float32, rot_x float32, rot_y float32, rot_z float32, rot_w float32, time float32) flatbuffers.UOffsetT {
	builder.Prep(4, 36)
	builder.PrependFloat32(time)
	builder.Prep(4, 16)
	builder.PrependFloat32(rot_w)
	builder.PrependFloat32(rot_z)
	builder.PrependFloat32(rot_y)
	builder.PrependFloat32(rot_x)
	builder.Prep(4, 12)
	builder.PrependFloat32(pos_z)
	builder.PrependFloat32(pos_y)
	builder.PrependFloat32(pos_x)
	builder.PrependInt32(num)
	return builder.Offset()
}
