// automatically generated by the FlatBuffers compiler, do not modify

package Server

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SSEnterOther struct {
	_tab flatbuffers.Table
}

func GetRootAsSSEnterOther(buf []byte, offset flatbuffers.UOffsetT) *SSEnterOther {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SSEnterOther{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SSEnterOther) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SSEnterOther) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SSEnterOther) User(obj *User) *User {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(User)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func SSEnterOtherStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SSEnterOtherAddUser(builder *flatbuffers.Builder, User flatbuffers.UOffsetT) {
	builder.PrependStructSlot(0, flatbuffers.UOffsetT(User), 0)
}
func SSEnterOtherEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
