// automatically generated by the FlatBuffers compiler, do not modify

package Server

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SSEnterAck struct {
	_tab flatbuffers.Table
}

func GetRootAsSSEnterAck(buf []byte, offset flatbuffers.UOffsetT) *SSEnterAck {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SSEnterAck{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SSEnterAck) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SSEnterAck) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SSEnterAck) Error() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SSEnterAck) MutateError(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *SSEnterAck) Users(obj *User, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 36
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *SSEnterAck) UsersLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func SSEnterAckStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SSEnterAckAddError(builder *flatbuffers.Builder, error int32) {
	builder.PrependInt32Slot(0, error, 0)
}
func SSEnterAckAddUsers(builder *flatbuffers.Builder, users flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(users), 0)
}
func SSEnterAckStartUsersVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(36, numElems, 4)
}
func SSEnterAckEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
