// automatically generated by the FlatBuffers compiler, do not modify

package Server

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SSLeaveOther struct {
	_tab flatbuffers.Table
}

func GetRootAsSSLeaveOther(buf []byte, offset flatbuffers.UOffsetT) *SSLeaveOther {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SSLeaveOther{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SSLeaveOther) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SSLeaveOther) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SSLeaveOther) AccountID() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SSLeaveOther) MutateAccountID(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func SSLeaveOtherStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SSLeaveOtherAddAccountID(builder *flatbuffers.Builder, accountID int32) {
	builder.PrependInt32Slot(0, accountID, 0)
}
func SSLeaveOtherEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
