// automatically generated by the FlatBuffers compiler, do not modify

package Server

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SSLeave struct {
	_tab flatbuffers.Table
}

func GetRootAsSSLeave(buf []byte, offset flatbuffers.UOffsetT) *SSLeave {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SSLeave{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SSLeave) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SSLeave) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SSLeave) AccountID() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SSLeave) MutateAccountID(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func SSLeaveStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SSLeaveAddAccountID(builder *flatbuffers.Builder, accountID int32) {
	builder.PrependInt32Slot(0, accountID, 0)
}
func SSLeaveEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
