// automatically generated by the FlatBuffers compiler, do not modify

package Server

const (
	SSPacketTypeEnter      = 100000
	SSPacketTypeEnterAck   = 100001
	SSPacketTypeLeave      = 100002
	SSPacketTypeClose      = 100003
	SSPacketTypeEnterOther = 100004
	SSPacketTypeLeaveOther = 100005
	SSPacketTypeMove       = 100006
	SSPacketTypeMoveAck    = 100007
	SSPacketTypeShoot      = 100008
	SSPacketTypeShootAck   = 100009
)

var EnumNamesSSPacketType = map[int]string{
	SSPacketTypeEnter:      "Enter",
	SSPacketTypeEnterAck:   "EnterAck",
	SSPacketTypeLeave:      "Leave",
	SSPacketTypeClose:      "Close",
	SSPacketTypeEnterOther: "EnterOther",
	SSPacketTypeLeaveOther: "LeaveOther",
	SSPacketTypeMove:       "Move",
	SSPacketTypeMoveAck:    "MoveAck",
	SSPacketTypeShoot:      "Shoot",
	SSPacketTypeShootAck:   "ShootAck",
}
